### ISSUE TITLE
Error extracting file in ubuntu 21.04

### ISSUE THREAD

**Issue by Meganium97** [SwareJonge/Dolphin-Lua-Core#15]
![Screenshot from 2021-05-16 20-01-44](https://user-images.githubusercontent.com/73264332/118419445-a3330b80-b681-11eb-9e6f-9f24b01b00f9.png)
Picture should explain
Methods to recreate: Attempt to "Extract Here" from file explorer.

**Comment by BLCRAFT210** [comment]
just do `unzip Linux.zip`

then change the permissions of the sys folder by right clicking and going to properties > permissions > access > create and delete files. then click change permissions for enclosed files and press change

**Comment by Meganium97** [comment]
This works, thank you.
