### ISSUE TITLE
Problems running extracted ISOs

### ISSUE THREAD

**Issue by Crain-32** [SwareJonge/Dolphin-Lua-Core#9]
It seems that extracted ISOs don't function at all. I've confirmed an extracted ISO to run on the Official Dev Release 5.0-12137, however repeating these steps leads to an Error built into emulation (Not a dolphin crash error). I think this is an artifact carried over from the original base of db's Zelda Edition, since it extracts, loads, and repeats the error the exact same way as the Lua-Core version.

**Comment by Hibyehello** [comment]
Extracted ISO's do not work properly on 5.0 stable, although there is way to make it work, that method can break files.
